name: ffigen_com
description: Generates COM classes from lightly edited header and IDL files.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  ffi: ^2.0.2
  win32: ^5.0.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2
