name: ffigen_com
description: Generates COM classes from lightly edited header and IDL files.
version: 1.0.0

environment:
  sdk: '>=2.18.0-98.0.dev <3.0.0'

dependencies: {ffi: ^1.1.2, win32: ^2.5.2} 

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
